name: Update README from Credly

on:
  schedule:
    - cron: '0 12 * * *'  # Runs daily at 12:00 UTC (noon)
  workflow_dispatch:
  push:
    branches:
      - feature/automate-readme-update

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install requests

      - name: Run badge updater
        run: python update_readme.py

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add README.md
          git commit -m 'Update README with latest badges' || echo "No changes to commit"
          git push
